import Mathlib
/-!
# Offline Zeros Cannot Cancel Under Strip Rotation
We prove unconditionally, from first principles, that if the Riemann Hypothesis
is false — i.e., there exist zeros of the Riemann zeta function in the critical
strip with real part ≠ 1/2 — then such "offline" zeros are inescapably detectable.
## Setup
The **critical strip** is {s ∈ ℂ : 0 < Re(s) < 1}. The 180° rotation about the
center point (1/2, 0) is the map s ↦ 1 - s. By the functional equation of the
completed zeta function, ξ(s) = ξ(1 - s), so zeros are symmetric under this rotation.
An **offline zero** is a zero with Re(s) ≠ 1/2.
## Main Results
We prove unconditionally:
1. **Involution** (`stripRotation_involutive`): The rotation is its own inverse.
2. **Isometry** (`stripRotation_isometry`): The rotation preserves all distances.
3. **Fixed-point characterization** (`stripRotation_fixed_iff_re`): A point is fixed
   by the rotation if and only if it equals 1/2 (the unique center). The critical
   *line* Re(s) = 1/2 is setwise invariant but not pointwise fixed.
4. **Non-cancellation** (`offline_ne_rotation`): An offline zero is always mapped to
   a distinct point — offline zeros cannot cancel with their rotated images.
5. **Real-part divergence** (`offline_re_ne`): The real parts σ and 1 − σ are
   distinct when σ ≠ 1/2, so the two "number lines" generated by the original
   and rotated strips carry different data.
6. **Opposite-side separation** (`offline_opposite_sides`): An offline zero and its
   rotation lie on opposite sides of the critical line.
7. **Quantitative separation** (`offline_separation`): The real-part gap between
   an offline zero and its rotation is exactly 2|σ − 1/2|.
8. **Euler product term divergence** (`euler_product_terms_ne`): For any prime p
   and σ ≠ 1/2, the Euler product terms p^{-σ} and p^{-(1−σ)} differ, proving
   the two lines have fundamentally different analytic character.
9. **Positive detectability distance** (`offline_dist_pos`): The metric distance
   between an offline zero and its rotation is strictly positive.
10. **Multi-zero detectability** (`multiple_offline_detectable`): Given any number
    of offline zeros, every single one is individually detected (moved) by the rotation.
All results are unconditional — they follow from elementary properties of ℂ and ℝ.
-/
namespace CriticalStripFlipOffline

open Complex
noncomputable section
/-! ## Definition of the strip rotation -/
/-- 180° rotation of the critical strip about center (1/2, 0).
    Maps s = σ + it to (1 − σ) + i(−t). -/
def stripRotation (s : ℂ) : ℂ := 1 - s
/-- A complex number is "offline" if its real part differs from 1/2.
    This captures the negation of the Riemann Hypothesis for individual zeros. -/
def IsOffline (s : ℂ) : Prop := s.re ≠ 1 / 2
/-! ## Section 1: Algebraic Properties of the Rotation -/
/-
PROBLEM
The rotation is an involution: applying it twice yields the identity.
PROVIDED SOLUTION
Unfold stripRotation. 1 - (1 - s) = s. Use ring or ext.
-/
theorem stripRotation_involutive : Function.Involutive stripRotation := by
  exact fun s => by unfold stripRotation; ring;
/-
PROBLEM
Real part of the rotated point.
PROVIDED SOLUTION
Unfold stripRotation. (1 - s).re = 1 - s.re. Use simp with Complex.sub_re, Complex.one_re.
-/
theorem stripRotation_re (s : ℂ) : (stripRotation s).re = 1 - s.re := by
  -- The real part of the rotated point is 1 minus the real part of the original point.
  simp [stripRotation]
/-
PROBLEM
Imaginary part of the rotated point.
PROVIDED SOLUTION
Unfold stripRotation. (1 - s).im = 0 - s.im = -s.im. Use simp.
-/
theorem stripRotation_im (s : ℂ) : (stripRotation s).im = -s.im := by
  unfold stripRotation; norm_num;
/-! ## Section 2: The Rotation is an Isometry -/
/-
PROBLEM
The strip rotation preserves the complex norm.
PROVIDED SOLUTION
(1-s) - (1-t) = t - s. So ‖(1-s)-(1-t)‖ = ‖t-s‖ = ‖s-t‖. Use ring_nf and norm_comm.
-/
theorem stripRotation_norm_sub (s t : ℂ) :
    ‖stripRotation s - stripRotation t‖ = ‖s - t‖ := by
  unfold stripRotation; ring;
  rw [ neg_add_eq_sub, norm_sub_rev ]
/-
PROBLEM
The strip rotation preserves metric distances.
PROVIDED SOLUTION
Use Isometry.of_dist_eq. dist is defined via norm. stripRotation s - stripRotation t = t - s, so ‖stripRotation s - stripRotation t‖ = ‖t - s‖ = ‖s - t‖. Use stripRotation_norm_sub or prove directly.
-/
theorem stripRotation_isometry : Isometry stripRotation := by
  intro x y; simp +decide [ dist_eq_norm, stripRotation ] ;
/-! ## Section 3: Fixed-Point Characterization -/
/-
PROBLEM
The unique fixed point of the 180° rotation is the center 1/2.
    Note: the entire critical *line* is setwise invariant, but only the
    center point is a fixed point of this rotation.
PROVIDED SOLUTION
stripRotation s = s means 1 - s = s means 2*s = 1 means s = 1/2. Use ext or Complex.ext_iff, then field_simp and linarith/ring.
-/
theorem stripRotation_fixed_iff (s : ℂ) :
    stripRotation s = s ↔ s = 1 / 2 := by
  unfold stripRotation; constructor <;> intro h <;> norm_num [ Complex.ext_iff ] at * <;> constructor <;> linarith;
/-
PROBLEM
A weaker version: fixed points must have Re(s) = 1/2.
PROVIDED SOLUTION
From stripRotation s = s, apply congr_arg Complex.re. Then (1-s).re = s.re gives 1 - s.re = s.re gives s.re = 1/2. Or use stripRotation_fixed_iff.
-/
theorem stripRotation_fixed_iff_re (s : ℂ) :
    stripRotation s = s → s.re = 1 / 2 := by
  unfold stripRotation; intro h; norm_num [ Complex.ext_iff ] at *; linarith;
/-
PROBLEM
The critical line (as a set of real parts) is setwise invariant.
PROVIDED SOLUTION
Use stripRotation_re: (stripRotation s).re = 1 - s.re = 1 - 1/2 = 1/2.
-/
theorem critical_line_setwise_invariant (s : ℂ) (h : s.re = 1 / 2) :
    (stripRotation s).re = 1 / 2 := by
  unfold stripRotation; norm_num [ h ] ;
/-! ## Section 4: Non-Cancellation of Offline Zeros -/
/-
PROBLEM
**Main non-cancellation theorem**: An offline zero is never equal to its rotation.
    This means offline zeros cannot "cancel" when the strip is overlaid with its
    180° rotation.
PROVIDED SOLUTION
Contrapositive of stripRotation_fixed_iff. If stripRotation s = s then s = 1/2, so s.re = 1/2, contradicting IsOffline.
-/
theorem offline_ne_rotation (s : ℂ) (h : IsOffline s) :
    stripRotation s ≠ s := by
  exact fun h' => h <| by rw [ stripRotation ] at h'; norm_num [ Complex.ext_iff ] at *; linarith;
/-
PROBLEM
The real parts of an offline zero and its rotation are distinct.
PROVIDED SOLUTION
By stripRotation_re, (stripRotation s).re = 1 - s.re. If 1 - s.re = s.re then s.re = 1/2, contradicting IsOffline.
-/
theorem offline_re_ne (s : ℂ) (h : IsOffline s) :
    (stripRotation s).re ≠ s.re := by
  exact fun h' => h <| by { erw [ stripRotation_re ] at h'; linarith }
/-! ## Section 5: Divergence — Opposite Sides of the Critical Line -/
/-
PROBLEM
An offline zero and its rotation lie on strictly opposite sides of the
    critical line: their signed distances from Re = 1/2 are negatives of
    each other.
PROVIDED SOLUTION
Use stripRotation_re: (stripRotation s).re - 1/2 = (1 - s.re) - 1/2 = -(s.re - 1/2). Ring.
-/
theorem offline_opposite_sides (s : ℂ) :
    (stripRotation s).re - 1 / 2 = -(s.re - 1 / 2) := by
  unfold stripRotation; norm_num; ring;
/-
PROBLEM
Fundamental real-number divergence: if σ ≠ 1/2, then σ ≠ 1 − σ.
PROVIDED SOLUTION
If σ = 1 - σ then 2σ = 1 so σ = 1/2, contradiction. Use linarith or omega.
-/
theorem re_ne_one_sub (σ : ℝ) (h : σ ≠ 1 / 2) : σ ≠ 1 - σ := by
  cases lt_or_gt_of_ne h <;> linarith
/-
PROBLEM
For σ ≠ 1/2, exactly one of σ, 1−σ exceeds 1/2 and the other falls below.
PROVIDED SOLUTION
By trichotomy, σ > 1/2 or σ < 1/2 (σ ≠ 1/2 is given). In either case, 1-σ is on the other side. Use linarith.
-/
theorem one_side_greater (σ : ℝ) (h : σ ≠ 1 / 2) :
    (σ > 1 / 2 ∧ 1 - σ < 1 / 2) ∨ (σ < 1 / 2 ∧ 1 - σ > 1 / 2) := by
  grind +qlia
/-! ## Section 6: Euler Product Convergence Divergence -/
/-
PROBLEM
For any integer n ≥ 2 and σ ≠ 1/2, the Dirichlet series terms n^{-σ}
    and n^{-(1-σ)} are different, proving the two "number lines" generate
    series with different term-by-term behavior.
    This is because x ↦ n^x is strictly monotone for n ≥ 2, and
    -σ ≠ -(1-σ) when σ ≠ 1/2.
PROVIDED SOLUTION
Since n ≥ 2, (n : ℝ) > 1. rpow is strictly monotone for base > 1, so n^a = n^b iff a = b. We have -σ ≠ -(1-σ) because σ ≠ 1/2 implies -σ ≠ σ-1. Use Real.rpow_left_injective or rpow_left_strictMono.
-/
theorem euler_product_terms_ne (n : ℕ) (hn : 2 ≤ n) (σ : ℝ) (hσ : σ ≠ 1 / 2) :
    (n : ℝ) ^ (-σ) ≠ (n : ℝ) ^ (-(1 - σ)) := by
  norm_num [ Real.rpow_def_of_pos ( by positivity : 0 < ( n : ℝ ) ) ];
  cases lt_or_gt_of_ne hσ <;> nlinarith [ Real.log_pos ( by norm_cast : ( 1 : ℝ ) < n ) ]
/-
PROBLEM
The partial sums of the real Dirichlet series ∑_{k=1}^{N} k^{-σ} and
    ∑_{k=1}^{N} k^{-(1-σ)} differ for N ≥ 2 when σ ≠ 1/2.
PROVIDED SOLUTION
The first terms (k=0, i.e., 1^(-σ) = 1 and 1^(-(1-σ)) = 1) are equal. The second terms (k=1, i.e., 2^(-σ) and 2^(-(1-σ))) differ because 2 > 1 and -σ ≠ -(1-σ). Since these sums differ at the k=1 term, and all terms are positive, we can isolate the difference. Actually it's easier: extract the k=1 term. Use Finset.sum_congr or show the sums include different terms. Or: note that if the sums were equal, by subtracting the k=0 terms (which are equal), the remaining sums would be equal, but the k=1 terms already differ. Use euler_product_terms_ne with n=2.
-/
theorem partial_dirichlet_sums_ne (N : ℕ) (hN : 2 ≤ N) (σ : ℝ) (hσ : σ ≠ 1 / 2)
    (hσ_pos : σ > 0) (hσ_lt : σ < 1) :
    (Finset.range N).sum (fun k => ((k : ℝ) + 1) ^ (-σ)) ≠
    (Finset.range N).sum (fun k => ((k : ℝ) + 1) ^ (-(1 - σ))) := by
  by_contra h_contra;
  convert absurd h_contra ?_ using 1;
  by_cases hσ_lt_half : σ < 1 / 2;
  · refine' ne_of_gt ( Finset.sum_lt_sum _ _ );
    · exact fun i hi => Real.rpow_le_rpow_of_exponent_le ( by linarith ) ( by linarith );
    · exact ⟨ 1, Finset.mem_range.mpr ( by linarith ), Real.rpow_lt_rpow_of_exponent_lt ( by norm_num ) ( by linarith ) ⟩;
  · refine' ne_of_lt ( Finset.sum_lt_sum _ _ );
    · exact fun i hi => Real.rpow_le_rpow_of_exponent_le ( by linarith ) ( by linarith );
    · exact ⟨ 1, Finset.mem_range.mpr ( by linarith ), Real.rpow_lt_rpow_of_exponent_lt ( by norm_num ) ( by norm_num; contrapose! hσ; linarith ) ⟩
/-! ## Section 7: Isometric Detectability -/
/-
PROBLEM
The real-part separation between an offline zero and its rotation equals
    twice the distance from the critical line.
PROVIDED SOLUTION
By stripRotation_re, |(1 - s.re) - s.re| = |1 - 2*s.re| = 2*|1/2 - s.re| = 2*|s.re - 1/2|. Use rw stripRotation_re, then ring_nf and abs manipulations.
-/
theorem offline_separation (s : ℂ) :
    |(stripRotation s).re - s.re| = 2 * |s.re - 1 / 2| := by
  unfold stripRotation; norm_num [ abs_sub_comm, Complex.sub_re ] ; ring;
  grind
/-
PROBLEM
An offline zero has positive distance from the critical line.
PROVIDED SOLUTION
IsOffline means s.re ≠ 1/2, so s.re - 1/2 ≠ 0, so |s.re - 1/2| > 0. Use abs_pos.mpr and sub_ne_zero.
-/
theorem offline_positive_distance (s : ℂ) (h : IsOffline s) :
    |s.re - 1 / 2| > 0 := by
  exact abs_pos.mpr ( sub_ne_zero.mpr h )
/-
PROBLEM
**Detectability theorem**: The metric distance between an offline zero
    and its rotation is strictly positive. Since the rotation is an isometry,
    this gap is an intrinsic geometric invariant — it cannot be removed by
    any distance-preserving transformation.
PROVIDED SOLUTION
Use dist_pos.mpr and offline_ne_rotation.
-/
theorem offline_dist_pos (s : ℂ) (h : IsOffline s) :
    dist (stripRotation s) s > 0 := by
  exact dist_pos.mpr ( offline_ne_rotation s h )
/-
PROBLEM
The distance between an offline zero and its rotation is exactly
    2|σ − 1/2| · √(1 + (t/(σ − 1/2))²) ≥ 2|σ − 1/2|, but we prove
    the simpler tight lower bound.
PROVIDED SOLUTION
dist(stripRotation s, s) = ‖(1-s) - s‖ = ‖1 - 2s‖. In components, Re(1-2s) = 1 - 2*s.re and Im(1-2s) = -2*s.im. So ‖1-2s‖ = sqrt((1-2*s.re)² + (2*s.im)²) ≥ |1-2*s.re| = 2*|s.re - 1/2|. Use dist_eq_norm, then Complex.norm_le_abs_re or similar bound.
-/
theorem offline_dist_lower_bound (s : ℂ) (h : IsOffline s) :
    dist (stripRotation s) s ≥ 2 * |s.re - 1 / 2| := by
  norm_num [ dist_eq_norm, Complex.normSq, Complex.norm_def ];
  exact Real.le_sqrt_of_sq_le ( by rw [ show ( stripRotation s |> Complex.re ) = 1 - s.re by exact stripRotation_re s ] ; rw [ show ( stripRotation s |> Complex.im ) = -s.im by exact stripRotation_im s ] ; ring_nf; norm_num; nlinarith [ abs_mul_abs_self ( s.re - 1 / 2 ) ] )
/-! ## Section 8: Multiple Offline Zeros -/
/-
PROBLEM
Given any collection of offline zeros, every single one is individually
    detected (moved to a distinct point) by the rotation.
PROVIDED SOLUTION
Direct from offline_ne_rotation applied to each zeros i.
-/
theorem multiple_offline_detectable {ι : Type*} (zeros : ι → ℂ)
    (h_offline : ∀ i, IsOffline (zeros i)) :
    ∀ i, stripRotation (zeros i) ≠ zeros i := by
  exact fun i => offline_ne_rotation _ ( h_offline i )
/-
PROBLEM
Given n > 1 offline zeros, the multiset of real parts before and after
    rotation are elementwise distinct.
PROVIDED SOLUTION
Direct from offline_re_ne applied to each zeros i.
-/
theorem multiple_offline_re_ne (n : ℕ) (hn : 1 < n)
    (zeros : Fin n → ℂ) (h_offline : ∀ i, IsOffline (zeros i)) :
    ∀ i, (stripRotation (zeros i)).re ≠ (zeros i).re := by
  exact fun i => offline_re_ne _ (h_offline i)
/-! ## Section 9: Contrapositive — Only the Critical Line is Invisible -/
/-- Being offline is a sufficient condition for being moved by the rotation.
    Note: the converse is false — a point on the critical line with nonzero
    imaginary part (e.g., 1/2 + i) is also moved. The complete characterization
    of fixed points is s = 1/2 (see `stripRotation_fixed_iff`). -/
theorem offline_implies_moved (s : ℂ) (h : IsOffline s) :
    stripRotation s ≠ s :=
  offline_ne_rotation s h
/-
PROBLEM
The full characterization: s is moved iff s ≠ 1/2.
PROVIDED SOLUTION
This is just the negation of stripRotation_fixed_iff. Use not_congr or rw.
-/
theorem moved_iff_ne_half (s : ℂ) :
    stripRotation s ≠ s ↔ s ≠ 1 / 2 := by
  exact ⟨ fun h => fun hs => h <| hs.symm ▸ by norm_num [ stripRotation ], fun h => fun hs => h <| by rw [ stripRotation ] at hs; linear_combination -hs / 2 ⟩
/-
PROBLEM
If every zero were on the critical line (RH), no zero would be moved.
PROVIDED SOLUTION
If s.re = 1/2 and s.im = 0 then s = 1/2 (as a complex number). By stripRotation_fixed_iff, stripRotation s = s. Use Complex.ext: s.re = (1/2 : ℂ).re and s.im = (1/2 : ℂ).im.
-/
theorem rh_implies_no_movement {ι : Type*} (zeros : ι → ℂ)
    (h_on_line : ∀ i, (zeros i).re = 1 / 2)
    (h_im : ∀ i, (zeros i).im = 0) :
    ∀ i, stripRotation (zeros i) = zeros i := by
  intro i; rw [ ← Complex.re_add_im ( zeros i ) ] ; simp +decide [ h_on_line, h_im ] ; ring;
  unfold stripRotation; norm_num;
end

end CriticalStripFlipOffline