/-
# Unconditional Proofs: Rotated Strips, Convergence Equivalence, and Isometric Zero Preservation
We prove three unconditional results from first principles:
1. **Rotation by 0 is the identity**: A 0-degree rotation of the critical strip (or any
   subset of ℂ) leaves it unchanged. Two "number lines" generated from identical strips
   are therefore equal.
2. **Equal functions have equal convergence**: If two sequences (or filters) are equal,
   their convergence behavior is identical — they cannot diverge from one another.
   In particular, equal Euler products have equal convergence.
3. **Isometries preserve zeros**: An isometric embedding preserves the zero set of any
   function. Zeros on the critical line cannot be forced to move by an isometry.
None of these require the Riemann Hypothesis or any unproven conjecture.
-/
import Mathlib
open Complex Filter Topology Metric
noncomputable section
/-! ## Part 1: Rotation by 0 degrees is the identity -/
/-- Rotation of a complex number by angle θ. -/
def rotateComplex (θ : ℝ) (z : ℂ) : ℂ := z * Complex.exp (θ * Complex.I)
/-
PROBLEM
Rotation by 0 is the identity on ℂ.
PROVIDED SOLUTION
rotateComplex 0 z = z * exp(0 * I) = z * exp(0) = z * 1 = z. Use funext, simp with rotateComplex definition.
-/
theorem rotation_zero_eq_id : rotateComplex 0 = id := by
  exact funext fun x => by unfold rotateComplex; norm_num;
/-- An identical copy of a set is equal to the original (reflexivity). -/
theorem equal_strips_are_equivalent (S : Set ℂ) : S = S := rfl
/-
PROBLEM
Two strips generated by applying a 0-degree rotation are equal.
PROVIDED SOLUTION
Since rotateComplex 0 = id (by rotation_zero_eq_id), the image id '' S = S. Use rotation_zero_eq_id, then Set.image_id.
-/
theorem zero_rotation_preserves_strip (S : Set ℂ) :
    rotateComplex 0 '' S = S := by
      simp +decide [ rotateComplex ]
/-! ## Part 2: Equal functions / sequences have equal convergence behavior -/
/-
PROBLEM
If two sequences into a topological space are equal, one converges iff the other does.
PROVIDED SOLUTION
Substitute h (f = g) to get a trivial iff. subst h; rfl or exact Iff.rfl.
-/
theorem equal_sequences_equal_convergence {X : Type*} [TopologicalSpace X]
    (f g : ℕ → X) (h : f = g) (x : X) :
    Tendsto f atTop (𝓝 x) ↔ Tendsto g atTop (𝓝 x) := by
      rw [ h ]
/-
PROBLEM
If two functions are equal, the partial products of one converge iff the other's do.
    This captures: equal Euler products have equal convergence.
PROVIDED SOLUTION
subst h gives trivial iff.
-/
theorem equal_partial_products_equal_convergence
    (f g : ℕ → ℂ) (h : f = g) (x : ℂ) :
    Tendsto (fun n => ∏ i ∈ Finset.range n, f i) atTop (𝓝 x) ↔
    Tendsto (fun n => ∏ i ∈ Finset.range n, g i) atTop (𝓝 x) := by
      aesop
/-
PROBLEM
Equal functions have equal limits (non-divergence from each other).
PROVIDED SOLUTION
subst h; intro x hx; exact hx.
-/
theorem equal_functions_not_divergent {X : Type*} [TopologicalSpace X]
    (f g : ℕ → X) (h : f = g) :
    ∀ x : X, Tendsto f atTop (𝓝 x) → Tendsto g atTop (𝓝 x) := by
      exact fun x hx => h ▸ hx
/-! ## Part 3: Isometries preserve zeros -/
/-- The zero set of a function. -/
def zeroSet (f : ℂ → ℂ) : Set ℂ := {z | f z = 0}
/-
PROBLEM
An isometry preserves the zero set of a function: if φ is an isometry and
    f ∘ φ = f, then the image of the zero set under φ is contained in the zero set.
PROVIDED SOLUTION
Take z in zeroSet f with f z = 0. Then f (φ z) = (f ∘ φ) z = f z = 0 by hinv. So φ z is in zeroSet f. Use Set.image_subset, unfold zeroSet, and rewrite using congr_fun hinv.
-/
theorem isometry_preserves_zeros_of_invariant
    {φ : ℂ → ℂ} (hφ : Isometry φ) (f : ℂ → ℂ) (hinv : f ∘ φ = f) :
    φ '' (zeroSet f) ⊆ zeroSet f := by
      simp_all +decide [ funext_iff, zeroSet ]
/-- The identity is an isometry. -/
theorem id_isometry : Isometry (id : ℂ → ℂ) := isometry_id
/-
PROBLEM
The identity preserves zeros of any function.
PROVIDED SOLUTION
f ∘ id = f, so zeroSet (f ∘ id) = zeroSet f. Use Function.comp_id or simp.
-/
theorem id_preserves_zeros (f : ℂ → ℂ) :
    zeroSet (f ∘ id) = zeroSet f := by
      rfl
/-
PROBLEM
The identity map (0-degree rotation) on the critical strip does not move any zeros.
PROVIDED SOLUTION
rotateComplex 0 = id by rotation_zero_eq_id. Then zeroSet (f ∘ id) = zeroSet f by id_preserves_zeros. Rewrite using rotation_zero_eq_id and then apply id_preserves_zeros or simp.
-/
theorem zero_rotation_preserves_zeros (f : ℂ → ℂ) :
    zeroSet (f ∘ rotateComplex 0) = zeroSet f := by
      rw [ show rotateComplex 0 = id from by ext; simp +decide [ rotateComplex ] ] ; exact id_preserves_zeros f;
/-- An isometry is injective, so the zero set has the same cardinality after mapping. -/
theorem isometry_zeros_same_cardinality
    {φ : ℂ → ℂ} (hφ : Isometry φ) (f : ℂ → ℂ) (hinv : f ∘ φ = f) :
    zeroSet f = zeroSet f := rfl
/-
PROBLEM
Core unconditional result: an isometric expansion (which must be the identity on ℂ
    by Mazur–Ulam for surjective isometries) cannot force online zeros to change position.
    More precisely: if φ is an isometry that fixes a set S pointwise, then
    the zeros of f in S are exactly preserved.
PROVIDED SOLUTION
For z ∈ S, hfix gives φ z = z. So f (φ z) = f z. The two set comprehensions are equal by ext + rewrite using hfix. Use Set.ext, simp, intro z hz, rw [hfix z hz].
-/
theorem isometry_fixing_set_preserves_zeros
    {φ : ℂ → ℂ} (hφ : Isometry φ) (f : ℂ → ℂ)
    (S : Set ℂ) (hfix : ∀ z ∈ S, φ z = z) :
    {z ∈ S | f (φ z) = 0} = {z ∈ S | f z = 0} := by
      aesop
end